apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume
  namespace: smart-city
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany