apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: smart-city
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node-server
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 30%
      maxSurge: 30%
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
        - name: node-server
          image: celebrimbor03/thesis-repo:node_server
          ports:
              - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"