apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: tesi
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: tesi
  template:
    metadata:
      labels:
        app: tesi
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          ports:
            - containerPort: 80
          env:
            - name: MY_APP
              valueFrom:    
                configMapKeyRef:
                  name: app-config
                  key: type
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "150m"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: app-config
            # se non specifico items li monto tutti i valori
        