apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: tesi
  template:
    metadata:
      labels:
        app: tesi
    spec:
      containers:
        - name: nginx
          image: nginx:1.14
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 64Mi
              cpu: 50M
            limits:
              memory: 128Mi
              cpu: 300M
        