apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrator
  namespace: tesi
spec:
  template:
    spec:
      containers:
        - name: myapp
          image: ubuntu:22.04
          command: [ "sleep", "60" ]
      restartPolicy: Never
  backoffLimit: 4