apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: tesi
spec:
  selector:
    matchLabels:
      app: tesi
  serviceName: database
  replicas: 1
  template:
    metadata:
      labels:
        app: tesi
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: db
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi