apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: tesi
spec:
  selector:
    matchLabels:
      app: tesi
  serviceName: database
  replicas: 1
  template:
    metadata:
      labels:
        app: tesi
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "150m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
            # qui il meccanismo per usarlo tramite file di config
              valueFrom: 
                secretKeyRef:
                  name: secret-db # nome del file
                  key: password
              # qui per usare il vaore schiantanto
              # value: root  
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: db
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi