apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: smart-city 
  labels:
    name: mongo-service
spec:
  selector:
    app: mongo-deploy
  type: NodePort
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32000