apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  namespace: smart-city
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mongo